---
 - hosts: all
   become: true
   tasks:
   - name: apt install python3-pip package
     apt:
       name: 
           - python3-pip

   - name: use pip3 as default pip
     command: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

   - name: use python3 as default python
     command: update-alternatives --install /usr/bin/python python /usr/bin/python3 1
