---
- hosts: all
  become: true
  tasks:

  - name: install python and pip3
    package:
    name:
      -python3
      -python3-pip
      name: default python3 
      pip:
        name:pip
        executable: pip3

  - name: install java
    apt:
      name: open javajdk-11-jdk
      when: ansible_distribution =='ubuntu'
  - name: Copy MOTD
      copy:
      content: "{{ motd_text | default('Ansible Manage Node by Escosia') }}"
      dest: /etc/motd
  - name: Create user
    user: 
      name: "{{ 'Escosia'}}"
      state: present
